
import { Account, Category, AppSettings } from './types';

// Use Keys for Default Data to allow Translation
export const INITIAL_ACCOUNTS: Account[] = [
  { id: 'acc_cash', key: 'cash', name: 'acctype_cash' },
  { id: 'acc_bank', key: 'bank', name: 'acctype_bank' },
  { id: 'acc_wallet', key: 'wallet', name: 'acctype_wallet' },
];

export const INITIAL_CATEGORIES: Category[] = [
  { id: 'cat_sal', name: 'cat_salary', type: 'income', subCategories: ['Full-time', 'Bonus'] },
  { id: 'cat_freelance', name: 'cat_freelance', type: 'income', subCategories: ['Project A', 'Project B'] },
  { id: 'cat_food', name: 'cat_food', type: 'expense', subCategories: ['Groceries', 'Restaurants', 'Coffee'] },
  { id: 'cat_transport', name: 'cat_transport', type: 'expense', subCategories: ['Fuel', 'Public Transit', 'Taxi'] },
  { id: 'cat_shop', name: 'cat_shopping', type: 'expense', subCategories: ['Clothes', 'Electronics'] },
  { id: 'cat_house', name: 'cat_housing', type: 'expense', subCategories: ['Rent', 'Utilities', 'Maintenance'] },
  { id: 'cat_ent', name: 'cat_entertainment', type: 'expense', subCategories: ['Movies', 'Games', 'Subscriptions'] },
];

export const DEFAULT_SETTINGS: AppSettings = {
  currency: 'USD', // Changed default to ISO code for Intl format
  currencies: ['USD'],
  deletedCurrencies: [],
  theme: 'auto',
  fontSize: 'medium',
  language: 'en',
  deletedLanguages: [],
  archivedCustomLanguages: {},
  defaultDashboardView: 'month',
  defaultReportView: 'all',
  defaultExportView: 'monthly',
  showBudgetOnDashboard: true,
  showCategoryBudgetsOnDashboard: true,
  hiddenCategoryBudgets: [],
  showFinancialOverviewChart: true,
  showAccountsOnDashboard: true,
  showQuickActionsOnDashboard: true,
  showAIInsightsOnDashboard: true,
  showFinancialHealthScore: true,
  reportChartType: 'bar',
  automationThreshold: 1000,
  autoBackup: 'off',
  enableRealtime: true,
};

export const STORAGE_KEYS = {
  TRANSACTIONS: 'sb_transactions',
  ACCOUNTS: 'sb_accounts',
  CATEGORIES: 'sb_categories',
  SETTINGS: 'sb_settings_v3',
  BUDGET: 'sb_budget',
  CATEGORY_BUDGETS: 'sb_cat_budgets',
  CUSTOM_TRANSLATIONS: 'sb_custom_translations',
  PENDING_DELETES: 'sb_pending_deletes',
  UNSYNCED_CHANGES: 'sb_unsynced_changes',
  ACTIVE_WALLET_ID: 'sb_active_wallet_id',
  WALLETS_LIST: 'sb_wallets_list',
  LAST_SYNC: 'sb_last_sync_time' 
};

export const LANGUAGE_NAMES: Record<string, string> = {
  en: 'English',
  hi: 'हिन्दी (Hindi)',
  ne: 'नेपाली (Nepali)',
  ar: 'العربية (Arabic)',
  ja: '日本語 (Japanese)',
  ko: '한국어 (Korean)',
  pt: 'Português (Portuguese)',
  zh: '中文 (Chinese)',
  es: 'Español (Spanish)',
  fr: 'Français (French)',
};

const enBase = {
  appTitle: 'Smart Budget Tracker',
  dashboard: 'Dashboard',
  reports: 'Reports',
  settings: 'Settings',
  account: 'Account',
  home: 'Home',
  balance: 'Balance',
  income: 'Income',
  expense: 'Expense',
  transfer: 'Transfer',
  all: 'All',
  monthlyForecast: 'Monthly Forecast',
  used: 'Used',
  categoryBudgets: 'Category Budgets',
  aiAnalysis: 'AI Analysis',
  recentActivity: 'Recent Activity',
  seeAll: 'See All',
  noActivity: 'No Activity Yet',
  budgetHealth: 'Budget Health',
  safe: 'Safe',
  alert: 'Alert',
  languageCurrency: 'Language and Currency',
  interfaceStyling: 'Interface Styling',
  bankAccounts: 'Bank & Cash Accounts',
  cloudSync: 'Backup and Restore',
  displayLayout: 'Display & Layout',
  setBudget: 'Set Budget',
  categoriesLabels: 'Categories & Labels',
  appPrefs: 'App Preferences',
  factoryReset: 'Reset Settings',
  selectedLanguage: 'Selected Language',
  mainCurrency: 'Active Currency',
  manageLibrary: 'Manage Local Library',
  resourceManager: 'Resource Manager',
  done: 'Done',
  get: 'Get',
  saveRecord: 'Save Record',
  editEntry: 'Edit Entry',
  newEntry: 'New Entry',
  amount: 'Amount',
  date: 'Date',
  note: 'Note',
  category: 'Category',
  subCategory: 'Sub-category',
  receipt: 'Digital Receipt',
  tapToAdd: 'Tap to add photo',
  personalSpace: 'Personal Space',
  familyWallet: 'Family Wallet',
  verified: 'Verified',
  notVerified: 'Not Verified',
  backupNow: 'Backup Now',
  restoreData: 'Restore Data',
  logout: 'Logout',
  securitySettings: 'Security Settings',
  changePassword: 'Change Password',
  deleteAccount: 'Close Account Forever',
  installed: 'Installed',
  today: 'Today',
  yesterday: 'Yesterday',
  week: 'Week',
  month: 'Month',
  custom: 'Custom',
  findTransaction: 'Find a transaction...',
  dataInsights: 'Data Insights',
  reminding: 'Remaining',
  extraExpense: 'Extra Expense',
  theme: 'Theme',
  fontSize: 'Text Size',
  dashboardComponents: 'Dashboard Components',
  mainBudgetForecast: 'Main Budget Forecast',
  categoryBudgetProgress: 'Category Budget Progress',
  financialOverviewChart: 'Financial Overview Chart',
  accountsRow: 'Accounts Row',
  quickActionBar: 'Quick Action Bar',
  aiIntelligenceInsights: 'AI Intelligence Insights',
  globalMonthlyBudget: 'Global Monthly Budget',
  categorySpecificLimits: 'Category-Specific Limits',
  syncStatus: 'Sync Status',
  lastSynced: 'Last Synced',
  backupAvailable: 'Backup Available',
  restoreFromCloud: 'Restore From Cloud',
  createCategory: 'Create Category',
  editCategory: 'Edit Category',
  subCategories: 'Sub-categories',
  addTag: 'Add Tag',
  manageAccounts: 'Manage Accounts',
  familyManagement: 'Family Wallet Hub',
  inviteMember: 'Invite Member',
  members: 'Members',
  owner: 'Owner',
  member: 'Member',
  role: 'Role',
  joinWallet: 'Join Wallet',
  sharingKey: 'Sharing Key',
  inviteByEmail: 'Invite by Email',
  cannotEditShared: 'Access Restricted: Members cannot edit shared data.',
  pendingInvitation: 'Pending Invitation',
  from: 'From Account',
  to: 'To Account',
  select: 'Select',
  openProfessionalAccount: 'Open Professional Account',
  newCategoryGroup: 'New Category Group',
  addLabel: 'Add Label...',
  mySavingsExample: 'e.g. My Savings',
  healthFitnessExample: 'e.g. Health & Fitness',
  onlineReady: 'Online Ready',
  syncPaused: 'Sync Paused',
  notSignedIn: 'Not Signed In',
  never: 'Never',
  autoBackup: 'Auto-Backup',
  enableAuto: 'Enable Auto',
  disableAuto: 'Disable Auto',
  nextScheduled: 'Next scheduled:',
  cloudInfrastructure: 'Cloud Infrastructure',
  localItems: 'Local Items:',
  cloudOnly: 'Cloud Only',
  mergeData: 'Merge Data',
  keepLocal: 'Keep Local',
  ignoreCloud: 'Ignore cloud backup',
  overwriteLocal: 'Overwrite local data',
  keepBoth: 'Keep both (Recommended)',
  syncConflict: 'Backup Data Found',
  foundBackup: 'We found an existing cloud backup associated with your account. Would you like to restore it?',
  synchronizing: 'Synchronizing...',
  identitySystem: 'Identity System',
  welcomeBack: 'Welcome Back',
  createAccount: 'Create Account',
  resetPassword: 'Reset Password',
  backToLogin: 'Back to Login',
  fullName: 'Full Name',
  emailAddress: 'Email Address',
  password: 'Password',
  confirmPassword: 'Confirm Password',
  forgotPassword: 'Forgot Password?',
  noAccount: "Don't have an account?",
  alreadyAccount: "Already have an account?",
  signUp: 'Sign Up',
  logIn: 'Log In',
  sendResetLink: 'Send Reset Link',
  uploadFailed: 'Upload failed',
  profileUpdated: 'Profile updated!',
  upToDate: 'Up to date',
  languages: 'Languages',
  currencies: 'Currencies',
  realTimeUpdates: 'Real-time Updates',
  createWallet: 'Create New Wallet',
  walletName: 'Wallet Name',
  walletCurrency: 'Wallet Currency',
  yourWallets: 'Your Wallets',
  switchWallet: 'Switch Wallet',
  personal: 'Personal',
  shared: 'Shared',
  manageMembers: 'Manage Members',
  addMember: 'Add Member',
  emailPlaceholder: 'user@example.com',
  remove: 'Remove',
  
  // New specific delete confirmations
  deleteConfirm: 'Delete',
  thisCannotBeUndone: 'This cannot be undone.',
  transactionsWillBeMoved: 'transactions will be moved to',
  transactionsWillBeUncategorized: 'transactions will become Uncategorized',
  orphaned: 'No Account (Orphaned)',

  // Category Keys
  'cat_salary': 'Salary',
  'cat_freelance': 'Freelance',
  'cat_food': 'Food & Dining',
  'cat_transport': 'Transport',
  'cat_shopping': 'Shopping',
  'cat_housing': 'Housing',
  'cat_entertainment': 'Entertainment',
  'cat_other': 'Other',
  'cat_uncategorized': 'Uncategorized',

  // Account Keys
  'acctype_cash': 'Cash',
  'acctype_bank': 'Bank Account',
  'acctype_wallet': 'Digital Wallet',

  // Subcategory Keys (English Defaults)
  'Full-time': 'Full-time',
  'Bonus': 'Bonus',
  'Project A': 'Project A',
  'Project B': 'Project B',
  'Groceries': 'Groceries',
  'Restaurants': 'Restaurants',
  'Coffee': 'Coffee',
  'Fuel': 'Fuel',
  'Public Transit': 'Public Transit',
  'Taxi': 'Taxi',
  'Clothes': 'Clothes',
  'Electronics': 'Electronics',
  'Rent': 'Rent',
  'Utilities': 'Utilities',
  'Maintenance': 'Maintenance',
  'Movies': 'Movies',
  'Games': 'Games',
  'Subscriptions': 'Subscriptions'
};

// Helper for dictionaries
const createLang = (overrides: Record<string, string>) => ({ ...enBase, ...overrides });

// ONLY English is default installed
export const TRANSLATIONS: Record<string, Record<string, string>> = {
  en: enBase
};

// All other languages are "Online" and must be installed
export const MOCK_ONLINE_LANGUAGES = [
  { code: 'hi', name: 'हिन्दी (Hindi)', dict: createLang({ 
      appTitle: 'स्मार्ट बजट', dashboard: 'डैशबोर्ड', reports: 'रिपोर्ट', settings: 'सेटिंग्स', account: 'खाता', balance: 'कुल शेष', income: 'आय', expense: 'खर्च', transfer: 'ट्रांसफर', today: 'आज', month: 'महीना',
      'cat_salary': 'वेतन', 'cat_food': 'खाना', 'cat_transport': 'यातायात', 'cat_shopping': 'खरीदारी', 'cat_housing': 'आवास', 'cat_entertainment': 'मनोरंजन',
      'acctype_cash': 'नकद', 'acctype_bank': 'बैंक खाता', 'acctype_wallet': 'डिजिटल वॉलेट',
      'Groceries': 'किराना', 'Restaurants': 'रेस्तरां', 'Rent': 'किराया', 'Fuel': 'ईंधन', 'Utilities': 'उपयोगिताएँ', 'Clothes': 'कपड़े', 'Movies': 'फिल्में'
  }) },
  { code: 'ne', name: 'नेपाली (Nepali)', dict: createLang({ 
      appTitle: 'स्मार्ट बजेट', dashboard: 'ड्यासबोर्ड', reports: 'रिपोर्टहरू', settings: 'सेटिङहरू', account: 'खाता', balance: 'बचत', income: 'आम्दानी', expense: 'खर्च', transfer: 'रकमान्तरण', today: 'आज', month: 'महिना',
      'cat_salary': 'तलब', 'cat_food': 'खाना', 'cat_transport': 'यातायात', 'cat_shopping': 'किनमेल', 'cat_housing': 'घर खर्च', 'cat_entertainment': 'मनोरंजन',
      'acctype_cash': 'नगद', 'acctype_bank': 'बैंक खाता', 'acctype_wallet': 'डिजिटल वालेट',
      'Groceries': 'किराना', 'Restaurants': 'रेस्टुरेन्ट', 'Rent': 'भाडा', 'Fuel': 'इन्धन', 'Clothes': 'लुगाफाटा'
  }) },
  { code: 'ar', name: 'العربية (Arabic)', dict: createLang({ 
      appTitle: 'الميزانية الذكية', dashboard: 'لوحة القيادة', reports: 'التقارير', settings: 'الإعدادات', account: 'الحساب', balance: 'الرصيد', income: 'دخل', expense: 'مصروف', transfer: 'تحويل', today: 'اليوم', month: 'شهر',
      'cat_salary': 'راتب', 'cat_food': 'طعام', 'cat_transport': 'نقل', 'cat_shopping': 'تسوق', 'cat_housing': 'سكن', 'cat_entertainment': 'ترفيه',
      'acctype_cash': 'نقدي', 'acctype_bank': 'حساب بنكي', 'acctype_wallet': 'محفظة رقمية',
      'Groceries': 'بقالة', 'Restaurants': 'مطاعم', 'Rent': 'إيجار', 'Fuel': 'وقود', 'Clothes': 'ملابس'
  }) },
  { code: 'ja', name: '日本語 (Japanese)', dict: createLang({ 
      appTitle: 'スマート予算', dashboard: 'ダッシュボード', reports: 'レポート', settings: '設定', account: 'アカウント', balance: '残高', income: '収入', expense: '支出', transfer: '振替', today: '今日', month: '月',
      'cat_salary': '給料', 'cat_food': '食事', 'cat_transport': '交通費', 'cat_shopping': '買い物', 'cat_housing': '住居費', 'cat_entertainment': '娯楽',
      'acctype_cash': '現金', 'acctype_bank': '銀行口座', 'acctype_wallet': 'デジタルウォレット',
      'Groceries': '食料品', 'Restaurants': 'レストラン', 'Rent': '家賃', 'Fuel': '燃料', 'Clothes': '衣類'
  }) },
  { code: 'ko', name: '한국어 (Korean)', dict: createLang({ 
      appTitle: '스마트 예산', dashboard: '대시보드', reports: '보고서', settings: '설정', account: '계정', balance: '잔액', income: '수입', expense: '지출', transfer: '이체', today: '오늘', month: '월',
      'cat_salary': '급여', 'cat_food': '식비', 'cat_transport': '교통비', 'cat_shopping': '쇼핑', 'cat_housing': '주거비', 'cat_entertainment': '오락',
      'acctype_cash': '현금', 'acctype_bank': '은행 계좌', 'acctype_wallet': '디지털 지갑',
      'Groceries': '식료품', 'Restaurants': '식당', 'Rent': '월세', 'Fuel': '연료', 'Clothes': '의류'
  }) },
  { code: 'pt', name: 'Português (Portuguese)', dict: createLang({ 
      appTitle: 'Orçamento Inteligente', dashboard: 'Painel', reports: 'Relatórios', settings: 'Configurações', account: 'Conta', balance: 'Saldo', income: 'Renda', expense: 'Despesa', transfer: 'Transferência', today: 'Hoje', month: 'Mês',
      'cat_salary': 'Salário', 'cat_food': 'Alimentação', 'cat_transport': 'Transporte', 'cat_shopping': 'Compras', 'cat_housing': 'Moradia', 'cat_entertainment': 'Entretenimento',
      'acctype_cash': 'Dinheiro', 'acctype_bank': 'Conta Bancária', 'acctype_wallet': 'Carteira Digital',
      'Groceries': 'Mercado', 'Restaurants': 'Restaurantes', 'Rent': 'Aluguel', 'Fuel': 'Combustível', 'Clothes': 'Roupas'
  }) },
  { code: 'zh', name: '中文 (Chinese)', dict: createLang({ 
      appTitle: '智能预算', dashboard: '仪表板', reports: '报告', settings: '设置', account: '账户', balance: '余额', income: '收入', expense: '支出', transfer: '转账', today: '今天', month: '月',
      'cat_salary': '工资', 'cat_food': '餐饮', 'cat_transport': '交通', 'cat_shopping': '购物', 'cat_housing': '住房', 'cat_entertainment': '娱乐',
      'acctype_cash': '现金', 'acctype_bank': '银行账户', 'acctype_wallet': '数字钱包',
      'Groceries': '杂货', 'Restaurants': '餐厅', 'Rent': '租金', 'Fuel': '燃料', 'Clothes': '衣服'
  }) },
  { code: 'es', name: 'Español (Spanish)', dict: createLang({ 
      appTitle: 'Presupuesto Inteligente',
      'cat_salary': 'Salario', 'cat_food': 'Comida', 'cat_transport': 'Transporte', 'cat_shopping': 'Compras', 'cat_housing': 'Vivienda', 'cat_entertainment': 'Entretenimiento',
      'acctype_cash': 'Efectivo', 'acctype_bank': 'Cuenta Bancaria', 'acctype_wallet': 'Billetera Digital',
      'Groceries': 'Comestibles', 'Restaurants': 'Restaurantes', 'Rent': 'Alquiler', 'Fuel': 'Combustible', 'Clothes': 'Ropa'
  }) },
  { code: 'fr', name: 'Français (French)', dict: createLang({ 
      appTitle: 'Budget Intelligent',
      'cat_salary': 'Salaire', 'cat_food': 'Restauration', 'cat_transport': 'Transport', 'cat_shopping': 'Achats', 'cat_housing': 'Logement', 'cat_entertainment': 'Divertissement',
      'acctype_cash': 'Espèces', 'acctype_bank': 'Compte Bancaire', 'acctype_wallet': 'Portefeuille Numérique',
      'Groceries': 'Épicerie', 'Restaurants': 'Restaurants', 'Rent': 'Loyer', 'Fuel': 'Carburant', 'Clothes': 'Vêtements'
  }) },
];

export const MOCK_ONLINE_CURRENCIES = [
  { code: 'USD', name: 'US Dollar', symbol: '$' },
  { code: 'EUR', name: 'Euro', symbol: '€' },
  { code: 'GBP', name: 'British Pound', symbol: '£' },
  { code: 'JPY', name: 'Japanese Yen', symbol: '¥' },
  { code: 'INR', name: 'Indian Rupee', symbol: '₹' },
  { code: 'NPR', name: 'Nepalese Rupee', symbol: 'रू' },
  { code: 'CNY', name: 'Chinese Yuan', symbol: '¥' },
  { code: 'KRW', name: 'Korean Won', symbol: '₩' },
  { code: 'AED', name: 'UAE Dirham', symbol: 'د.إ' },
  { code: 'BRL', name: 'Brazilian Real', symbol: 'R$' },
];
